name: Soundbooth
favicon: null
layout_spectrum: 0.50542
typography_spectrum: 0.71076
title: Colorado Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71473311-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff3193'
    - '#363636'
    - '#b3b3b3'
    - '#767676'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
