name: Soundbooth
favicon: null
layout_spectrum: 0
typography_spectrum: 0.71076
title: 'Soundbooth - Music, news for Colorado'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71473311-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff3193'
    - '#363636'
    - '#b3b3b3'
    - '#767676'
  brandStrength: 0.875
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
