name: Soundbooth
favicon: null
layout_spectrum: 0
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff3193'
    - '#363636'
    - '#b3b3b3'
    - '#767676'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
